config/routes.rb
Rails.application.routes.draw do

  # API Routes
  namespace :api do
    resources :contact_requests, only: [:create]
    resources :projects, only: [:index]
    get 'resume' => 'resumes#index'
  end

  # Admin Routes
  resources :resumes do
    member do
      get :mark_as_active
    end
  end
  resources :contact_requests, only: [:index, :show, :delete, :update]
  resources :projects do
    member do
      get :toggle_status
    end
  end
  devise_for :users
  
  # Health Check Route
  get "up" => "rails/health#show", as: :rails_health_check

  # Root Route
  root 'resumes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact_request.rb
class ContactRequest < ApplicationRecord
  validates_presence_of :name, :email, :message, :subject
end

app/models/project.rb
class Project < ApplicationRecord
  validates_presence_of :name, :description, :image
  has_one_attached :image

  scope :active, -> { where(active: true) }
end

app/models/resume.rb
class Resume < ApplicationRecord
  has_one_attached :file
  validates_presence_of :title, :file

  scope :active, -> { where(active: true) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::Base
  
end

app/controllers/api/contact_requests_controller.rb
class Api::ContactRequestsController < Api::ApplicationController
  protect_from_forgery with: :null_session

  def create
    @contact_request = ContactRequest.new(contact_request_params)
    if @contact_request.save
      render json: 
        {
          message: 'Your request has been submitted, I will get back to you shortly.',
          success: true
        }
    else
      render json: 
        {
          message: 'An error occured while submitting your request.',
          success: false,
          error: @contact_request.errors.full_messages
        }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def contact_request_params
    params.require(:contact_request).permit(:name, :email, :subject, :message)
  end
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < Api::ApplicationController
  include Rails.application.routes.url_helpers

  def index
    projects = Project.active.map do |project|
      {
        name: project.name,
        description: project.description,
        image: project.image.attached? ? url_for(project.image) : nil,
        github: project.github,
        link: project.link
      }
    end
    render json: { projects: projects }
  end
end

app/controllers/api/resumes_controller.rb
class Api::ResumesController < Api::ApplicationController
  include Rails.application.routes.url_helpers

  def index
    resume = Resume.active.first
    if resume&.file&.attached?
      render json: { resume_url: rails_blob_url(resume.file) }, status: :ok
    else
      render json: { error: 'Resume not found' }, status: :not_found
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :prepare_exception_notifier
  add_flash_types :info, :warning

  private

  def prepare_exception_notifier
    request.env["exception_notifier.exception_data"] = {
      current_user: current_user
    }
  end
end

app/controllers/contact_requests_controller.rb
class ContactRequestsController < ApplicationController
  before_action :set_contact_request, only: %i[ show update destroy ]

  def index
    @contact_requests = ContactRequest.all
  end

  def show
  end

  def update
    @contact_request.update(mark_as_seen: true)
    redirect_to @contact_request, notice: "Contact request marked as seen."
  end

  def destroy
    @contact_request.destroy!
    redirect_to contact_requests_url, notice: "Contact request was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_request
      @contact_request = ContactRequest.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @texts = Text.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :get_project, only: [:show, :edit, :update, :destroy, :toggle_status]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = 'Project was successfully created.'
      redirect_to projects_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
  end
  
  def update
    if @project.update(project_params)
      flash[:notice] = 'Project was successfully updated.'
      redirect_to projects_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = 'Project was successfully destroyed.'
    redirect_to projects_path
  end

  def toggle_status
    @project.active = !@project.active
    @project.save
    redirect_to projects_path
  end

  private

  def get_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :image, :github, :link, :active)
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: %i[ show edit update destroy mark_as_active ]

  def index
    @resumes = Resume.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @resume = Resume.new
  end

  def edit
  end

  def create
    @resume = Resume.new(resume_params)
    if @resume.save
      redirect_to resume_url(@resume), notice: "Resume was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @resume.update(resume_params)
      redirect_to resume_url(@resume), notice: "Resume was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def mark_as_active
    Resume.active.update_all(active: false)
    @resume.update(active: true)
    redirect_to resumes_url, notice: "Active resume was successfully updated."
  end

  def destroy
    @resume.destroy!
    redirect_to resumes_url, notice: "Resume was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def resume_params
      params.require(:resume).permit(:title, :file, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_flash_type(type)
    return 'success' if type == 'notice'
    return 'error' if type == 'alert'
    return 'info' if type == 'info'
    return 'warning' if type == 'warning'
  end

  def format_date(date)
    date.strftime("%d %b, %Y")
  end  

end

app/helpers/home_helper.rb
module HomeHelper
  def show_text_keys(texts)
    text_str = ""
    Text::SUB_CATEGORIES.each do |category, sub_categories|
      text_str += "<div><div class='setting.header'><h3>#{category.to_s.titleize}</h3></div><ul class='list-inline d-flex'>"
      sub_categories.each do |section, keys|
        keys.each do |key, value|
          text = texts.find_by(key: key)
          text_str += "<li class='mx-1'>#{link_to value, get_path(text, category, section, key), remote: true, class: button_class(text, category, section, key)} </li>"
        end
      end
      text_str += "</ul>"
    end
    text_str += "</div>"
    text_str.html_safe
  end

  def button_class(text, category, section, key)
    if text
      'btn btn-success'
    else
      'btn btn-danger'
    end
  end

  def get_path(text, category, section, key)
    if text
      edit_text_path(text, path: root_path)
    else
      new_text_path(text: {category: category, section: section, key: key}, path: root_path)
    end
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper
  def get_active_status(record)
    str = ''
    if record.active
      str = "<button class='btn btn-success rounded-5'>Active</button>"
    else
      str = "<button class='btn btn-danger rounded-5'>Inactive</button>"
    end
    str.html_safe
  end
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/contact_requests/index.html.erb
<h1>Contact requests</h1>
<br>
<div id="contact_requests">
</div>
<% @contact_requests.each do |contact_request| %>
  <div class="outer-div">
    <div class="inner-div">
      <div class="front">
        <div class="front__bkg-photo"></div>
        <div class="front__face-photo"></div>
        <div class="front__text">
          <h3 class="front__text-header"><%= contact_request.name %></h3><br>
          <p class="front__text-para"><i class="fas fa-envelope"></i> <%= contact_request.email %></p>
          <p class="front__text-para"><i class="fas fa-clock"></i> Request On: <%= format_date(contact_request.created_at) %></p>
          <%# <span class="front__text-hover">Show</span> %>
          <%= link_to "Show", contact_request, class: 'front__text-hover' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/contact_requests/show.html.erb
<%= link_to contact_requests_path, class: 'btn btn-outline-dark btn-sm' do %>
  <i class="fas fa-arrow-left"></i> Back
<% end %>
<div class="container mt-5">    
  <div class="row d-flex justify-content-center">      
    <div class="col-md-7">
      <div class="card p-3 py-4">
        <div class="text-center">
            <img src="https://i.imgur.com/bDLhJiP.jpg" width="100" class="rounded-circle">
        </div>
        <div class="text-center mt-3">
          <span class="bg-secondary p-1 px-4 rounded text-white">Request On: <%= format_date(@contact_request.created_at) %></span>
          <h5 class="mt-2 mb-0"><%= @contact_request.name %></h5>
          <span><%= @contact_request.email %></span>
            
          <div class="px-4 my-5">
              <p class="fonts">
                "<%= @contact_request.message %>"
              </p>
          </div>
            
          <div class="buttons">
            <% if @contact_request.mark_as_seen %>
              <button disabled class="btn btn-outline-primary px-4">Mark as Seen</button>
            <% else %>
              <%= link_to "Mark as Seen", contact_request_path(@contact_request), class: 'btn btn-outline-primary px-4', method: :patch %>
            <% end %>
          </div>    
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="page-header">
  <h3><%=t '.title', :default => 'Portfolio Completeness' %></h3>
</div>
<%= show_text_keys(@texts) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio | Pankaj Porwal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
  <div class="container">
    <%= render 'shared/navbar' if user_signed_in? %>
    <div class="flash_messages">
      <%#= render 'shared/toaster_flash' %>
      <%= render 'shared/toastr_flash_new' %>
    </div>
    <div class="content-container container">
      <%= yield %>
    </div>
  </div>
  <%= render 'shared/modal' %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |f| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :github, class: "form-label" %>
    <%= f.text_field :github, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :link, class: "form-label" %>
    <%= f.text_field :link, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :image, class: "form-label" %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="mb-3 form-check">
    <%= f.label :active, class: "form-check-label" %>
    <%= f.check_box :active, class: "form-check-input" %>
  </div>

  <div>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= link_to projects_path, class: '' do %>
  <i class="fas fa-arrow-left"></i> Back
<% end %>
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

app/views/projects/index.html.erb
<div class="d-flex justify-content-between ms-0 m-4">
  <div class="float-left">
    <h1>Projects</h1>
  </div>
  <div class="float-right">
    <%= link_to "New project", new_project_path, class: "btn btn-primary float-right" %>
  </div>
</div>

<div id="projects">
  <% @projects.each do |project| %>
		<article class="postcard light red">
      <%= link_to project, class: 'postcard__img_link' do %>
        <% if project.image.attached? %>
          <%= image_tag(project.image, class: "postcard__img") %>
        <% else %>
          <p>No image attached for this project.</p>
        <% end %>
      <% end %>
			<div class="postcard__text t-dark">
				<h1 class="postcard__title red"><%= project.name %></h1>
				<div class="postcard__subtitle small">
						<h6><%= project.description %></h6>
				</div>
				<div class="postcard__bar"></div>
				<div class="postcard__preview-txt"><%= get_active_status(project) %></div>
        <ul class="postcard__tagbox">
          <%= link_to project_path(project), class: 'btn btn-info btn-sm m-2' do %>
            <i class="fas fa-eye"></i> Show
          <% end %>
          <%= link_to edit_project_path(project), class: 'btn btn-warning btn-sm m-2' do %>
            <i class="fas fa-edit"></i> Edit
          <% end %>
          <%= button_to project, method: :delete, class: 'btn btn-danger btn-sm m-2', data: { confirm: 'Are you sure you want to delete this project?' } do %>
            <i class="fas fa-trash"></i> Delete
          <% end %>
          <% if project.active %>
            <%= link_to toggle_status_project_path(project), class: 'btn btn-sm m-2' do %>
              <i class="fa-solid fa-toggle-on fa-2xl"></i>
            <% end %>
          <% else %>
            <%= link_to toggle_status_project_path(project), class: 'btn btn-sm m-2' do %>
              <i class="fa-solid fa-toggle-off fa-2xl"></i>
            <% end %>
          <% end %>
        </ul>
			</div>
		</article>
  <% end %>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back", projects_path, class: 'btn btn-light' %>
</div>

app/views/projects/show.html.erb
<%= link_to projects_path, class: 'btn btn-outline-dark btn-sm' do %>
  <i class="fas fa-arrow-left"></i> Back
<% end %>
<div class="container mt-5">    
  <div class="row d-flex justify-content-center">      
    <div class="col-md-7">
      <div class="card p-3 py-4">
        <div class="text-center mt-3">
          <span class="bg-secondary p-2 px-4 rounded text-white"><%= @project.name %></span>
          <h5 class="mt-2 mb-0"><%=  %></h5>
          <span><%=  %></span>
            
          <div class="px-4 my-5">
              <p class="fonts">
                "<%= @project.description %>"
              </p>
          </div>

          <div class="px-4 my-5">
            <%= link_to (@project.github.present? ? @project.github : '#'), target: '_blank', class: 'btn btn-outline-dark px-4 mx-2' do %>
              <i class="fab fa-github"></i> GitHub
            <% end %>
            <%= link_to (@project.link.present? ? @project.link : '#'), target: '_blank', class: 'btn btn-outline-dark px-4 mx-2' do %>
              <i class="fa-solid fa-link"></i> Link
            <% end %>
          </div>
            
          <div class="buttons">
            <% if @project.active %>
              <%= link_to "Mark as Inactive", toggle_status_project_path(@project), class: 'btn btn-outline-danger px-4' %>
            <% else %>
              <%= link_to "Mark as Active", toggle_status_project_path(@project), class: 'btn btn-outline-success px-4' %>
            <% end %>
          </div>  

        </div>
      </div>
    </div>
  </div>
</div>

app/views/resumes/_form.html.erb
<%= form_with(model: resume) do |f| %>
  <% if resume.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
        <% resume.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :title, class: "form-label" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :file, class: "form-label" %>
    <%= f.file_field :file, class: "form-control" %>
  </div>

  <div class="mb-3 form-check">
    <%= f.label :active, class: "form-check-label" %>
    <%= f.check_box :active, class: "form-check-input" %>
  </div>

  <div>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<%= link_to resumes_path, class: '' do %>
  <i class="fas fa-arrow-left"></i> Back
<% end %>
<h1>Editing resume</h1>

<%= render "form", resume: @resume %>

<br>

app/views/resumes/index.html.erb
<div class="d-flex justify-content-between ms-0 m-4">
  <div class="float-left">
    <h1>Resumes</h1>
  </div>
  <div class="float-right">
    <%= link_to "New Resume", new_resume_path, class: "btn btn-primary float-right" %>
  </div>
</div>

<div id="resumes">
  <% @resumes.each do |resume| %>
		<article class="postcard light red">
      <%= link_to resume, class: 'postcard__img_link' do %>
        <% if resume.file.attached? %>
          <%= image_tag(resume.file.preview(resize_to_limit: [400, 400]).processed, class: "postcard__img") %>
        <% else %>
          <p>No file attached for this resume.</p>
        <% end %>
      <% end %>
			<div class="postcard__text t-dark">
				<h1 class="postcard__title red"><%= resume.title %></h1>
				<div class="postcard__subtitle small">
						<h5><i class="fas fa-calendar-alt mr-2"></i> Uploaded On: <%= format_date(resume.created_at) %></h5>
				</div>
				<div class="postcard__bar"></div>
				<div class="postcard__preview-txt"><%= get_active_status(resume) %></div>
        <ul class="postcard__tagbox">
          <%= link_to resume_path(resume), class: 'btn btn-info btn-sm m-2' do %>
            <i class="fas fa-eye"></i> Show
          <% end %>
          <%= link_to edit_resume_path(resume), class: 'btn btn-warning btn-sm m-2' do %>
            <i class="fas fa-edit"></i> Edit
          <% end %>
          <%= button_to resume, method: :delete, class: 'btn btn-danger btn-sm m-2', data: { confirm: 'Are you sure you want to delete this resume?' } do %>
            <i class="fas fa-trash"></i> Delete
          <% end %>
          <% if !resume.active %>
            <%= link_to mark_as_active_resume_path(resume), class: 'btn btn-outline-success btn-sm m-2' do %>
              <i class="fas fa-check"></i> Mark as Active
            <% end %>
          <% end %>
        </ul>
			</div>
		</article>
  <% end %>
</div>

app/views/resumes/new.html.erb
<h1>New resume</h1>

<%= render "form", resume: @resume %>

<br>

<div>
  <%= link_to "Back", resumes_path, class: 'btn btn-light' %>
</div>

app/views/resumes/show.html.erb
<%= link_to resumes_path, class: 'btn btn-outline-dark btn-sm' do %>
  <i class="fas fa-arrow-left"></i> Back
<% end %>
<div class="d-flex justify-content-between ms-0 m-4">
  <div class="float-left">
    <h1><%= @resume.title %> <%= "(Active)" if @resume.active %></h1>
  </div>
  <div class="float-right">
    <%= link_to "Edit",edit_resume_path(@resume), class: "btn btn-dark float-right" %>
  </div>
</div>

<div class="d-flex flex-column justify-content-center align-items-center vh-100">
  <% pdf_image = @resume.file.preview(resize_to_limit: [1000, 1000]).processed  %>
  <%= image_tag(pdf_image, class: 'img-fluid') %>
  <div class="mt-3">
    <%= button_to "Delete", @resume, method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure?"} %>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{get_flash_class(type)}") %>
<% end %>

app/views/shared/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header border-botton border-4 border-primary">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Close</button>
        <button type="button" class="btn btn-primary" id="modal-submit">Save</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Portfolio', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Projects', projects_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Resume', resumes_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact Requests', contact_requests_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.name.split(' ').first %>
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <%= link_to 'Sign Out', destroy_user_session_path, class: "dropdown-item", method: :delete %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_toaster_flash.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].to_s == 'alert' ? 'error' : 'success' %>
      toastr['<%= type %>']('<%= f[1] %>', {timeOut: 5000,closeButton: true,progressBar: true, positionClass: "toast-bottom-right"});
      <% end %>
  </script>
<% end %>

app/views/shared/_toastr_flash_new.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
    <% type = get_flash_type(f[0].to_s) %>
    $.toast({
      title:"<%= type.titleize %>",
      message:"<%= f[1] %>",
      type:"<%= type %>",
      duration: 5000,// auto-dismiss after 5s
    });
    <% end %>
  </script>
<% end %>

app/views/texts/_text.html.erb
<div id="<%= dom_id text %>">
  <p>
    <strong>Key:</strong>
    <%= text.key %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= text.value %>
  </p>

</div>

app/views/texts/edit.html.erb
<h1>Editing text</h1>

<%= render "form", text: @text %>

<br>

<div>
  <%= link_to "Show this text", @text %> |
  <%= link_to "Back to texts", texts_path %>
</div>

app/views/texts/edit.js.erb
$('#exampleModalCenter').find('.modal-title').text("<%=t '.title', :default => [:'helpers.titles.new', 'Edit %{model}'], :model => 'Text' %>");
$('#exampleModalCenter').find('.modal-body').html("<%= escape_javascript(render 'form') %>");
$('#exampleModalCenter').modal('show');
$('#modal_submit').attr("disabled", false);

app/views/texts/new.html.erb
<h1>New text</h1>

<%= render "form", text: @text %>

<br>

<div>
  <%= link_to "Back to texts", texts_path %>
</div>

app/views/texts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @text %>

<div>
  <%= link_to "Edit this text", edit_text_path(@text) %> |
  <%= link_to "Back to texts", texts_path %>

  <%= button_to "Destroy this text", @text, method: :delete %>
</div>